# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job
      
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src
        
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: NuGet Login
      id: login
      uses: NuGet/login@v1
      with:
        user: dbarwikowski
     # Push the package
    - name: NuGet push
      run: dotnet nuget push NeverendingShift.Hangfire/bin/Release/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
